version: '3.7'
name: "django-partitioning-backend"

volumes:
  ipython_history: {}

services:
  app: &app
    image: "${COMPOSE_PROJECT_NAME}"
    entrypoint: /cnb/lifecycle/launcher
    volumes:
      - ./:/workspace
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      postgres:
          condition: service_healthy
      redis:
          condition: service_started

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h postgres -t 5 -U ${COMPOSE_PROJECT_NAME}-user || false"
      ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=${COMPOSE_PROJECT_NAME}-dev
      - POSTGRES_USER=${COMPOSE_PROJECT_NAME}-user
      - POSTGRES_PASSWORD=manager

  redis:
    image: redis:6.0.5
    ports:
      - "6379:6379"

  web: &web
    <<: *app
    ports:
      - "8000:8000"
    entrypoint: runserver_local

  celery: &celery
    <<: *app
    entrypoint: celery_debug
