# Generated by Django 4.2.11 on 2024-04-23 03:12

import django.utils.timezone
from django.db import migrations

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True,
                verbose_name="modified",
            ),
        ),
    ]
