# Generated by Django 4.2.11 on 2024-04-23 03:45

from django.db import migrations

from psqlextra.backend.migrations.operations import (
    PostgresAddRangePartition,
)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_person_created_person_modified"),
    ]

    operations = [
        # PostgresDeleteDefaultPartition(
        #    model_name="person",
        #    name="default",
        # ),
        PostgresAddRangePartition(
            model_name="person",
            name="people_partitioned_birthdays_1700_to_1799",
            from_values="1700-01-01",
            to_values="1799-12-31",
        ),
        PostgresAddRangePartition(
            model_name="person",
            name="people_partitioned_birthdays_1800_to_1899",
            from_values="1800-01-01",
            to_values="1899-12-31",
        ),
        PostgresAddRangePartition(
            model_name="person",
            name="people_partitioned_birthdays_1900_to_1999",
            from_values="1900-01-01",
            to_values="1999-12-31",
        ),
        PostgresAddRangePartition(
            model_name="person",
            name="people_partitioned_birthdays_2000_to_2099",
            from_values="2000-01-01",
            to_values="2099-12-31",
        ),
    ]
