name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Fallback to plain text output for reducing docker output
  # https://github.com/docker/compose/issues/8753#issuecomment-934473781
  BUILDKIT_PROGRESS: plain

jobs:
  cr:
    runs-on: saritasa-rocks-eks
    timeout-minutes: 10
    env:
      DJANGO_SETTINGS_MODULE: config.settings.local
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.SARITASA_LLC_DOCKERHUB_USERNAME }}
        password: ${{ secrets.SARITASA_LLC_DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Set up Python
      id: install-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.4.0
      with:
        key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose.yml') }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-${{ steps.install-python.outputs.python-version }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Cache poetry dependencies
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-${{ steps.install-python.outputs.python-version }}-${{ github.job }}-poetry-${{ hashFiles('**/poetry.lock') }}
    # Install dependencies if cache does not exist
    - name: Install local dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction
    - name: Prepare CI env
      run: |
        poetry run inv ci.prepare
    - name: Run checks
      run: |
        poetry run inv pre-commit.run-hooks
