name: Update dependencies

on:
  schedule:
  # Run action at 21:00 UTC every Monday https://crontab.guru/#0_21_*_*_1
  - cron: '0 21 * * 1'
  # or trigger action manually
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_dependencies:
    name: Update dependencies
    runs-on: saritasa-rocks-eks
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: install-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install local dependencies
        run: poetry install --no-interaction --only="local"
      - name: Update dependencies
        run: |
          poetry self add poetry-plugin-up
          poetry run inv poetry.update-to-latest -p --no-install
          poetry run inv pre-commit.update
      - name: Generate token
        # Docs for action: https://github.com/marketplace/actions/github-app-token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.SARITASA_GITHUB_BOT_ID }}
          private_key: ${{ secrets.SARITASA_GITHUB_BOT_PRIVATE_KEY }}
      - name: Create Pull Request
        # Docs for action: https://github.com/marketplace/actions/create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "[automated-commit] Update dependencies"
          title: Update dependencies
          body: |
            Task: SA3P-66
            Created by GitHub Actions
          base: develop
          labels: automated-pr
          branch: feature/SA3P-66-updates-dependencies
          delete-branch: true
